### PR TITLE
Improvement: Update hygen to have camel case in domain entity

### PR DESCRIPTION
**Pull request by dev-ahmadbilal**
1. Updated the hygen templates to follow camel case naming in domain entity and dtos
2. Updated the add property templates to have camel case in domain entity and dtos
3. Updated the mappers to accordingly

### CODE REVIEW

**Comment by hhsadiq** [comment]
Looks good. Hopefully we have tested as well by creating the CRUDs and adding properties etc.

**Comment by dev-ahmadbilal** [comment]
> Looks good. Hopefully we have tested as well by creating the CRUDs and adding properties etc.

Yes it's tested by creating resources and adding properties.

**Comment by hhsadiq** [comment]
awesome, will be merged, as per the timelines shared in the audio note on slack

**Comment by hhsadiq** [comment]
should we update all the existing resources as well to camel cases as well. Just to be in sync with this approach. Omer and Hassan has updated them in the MOTAC project. We can ask them to update here as well

**Pull request merged**
